#!/usr/bin/env node
// Copy third-party browser scripts out of node_modules into public/vendor/ so
// Vite ships them from OUR origin.
//
// Audit F-029. index.html used to load executable JavaScript straight from
// jsDelivr and cdnjs on every page — including /wallet, where the same origin
// runs `signAndSend`. Worse, Chart.js was requested as
// `https://cdn.jsdelivr.net/npm/chart.js` with no version at all: whatever
// jsDelivr resolved `latest` to that minute got wallet-origin script execution.
// A surprise publish or a CDN compromise was a wallet compromise.
//
// Why copy from node_modules rather than commit blobs or add SRI hashes:
//   - the version is pinned by package-lock.json, so `npm ci` reproduces the
//     exact bytes and Dependabot/npm audit can actually see the dependency
//   - no minified vendor blobs in git, and no hash to forget to update
//   - same-origin is the precondition for a `script-src 'self'` CSP (F-039);
//     SRI alone would still leave a third-party origin in the policy
//
// Runs automatically: `npm run build` triggers the `prebuild` script, and
// Dockerfile.frontend does `npm ci` before `npm run build`, so the container
// build populates public/vendor without any extra step. public/vendor is
// gitignored — it is a build artifact, not source.

import { mkdirSync, copyFileSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// UMD/classic builds on purpose: both are loaded by a plain <script> tag and
// assign a global (window.Chart / window.QRCode) that script.js already uses.
// Importing them as ES modules instead would scope those names to the module
// and silently break every chart and the donate-page QR code.
const ASSETS = [
    { from: 'node_modules/chart.js/dist/chart.umd.js', to: 'public/vendor/chart.umd.js' },
    { from: 'node_modules/qrcodejs/qrcode.min.js', to: 'public/vendor/qrcode.min.js' },

    // ── F-039 additions: the last two third-party origins ────────────────
    // Boxicons came from unpkg and Inter from Google Fonts. Neither is
    // executable, but both had to leave before the CSP could say
    // `default-src 'self'` — a policy with two external stylesheet origins
    // still hands those CDNs a same-origin CSS injection surface, and Google
    // Fonts is a per-visitor tracking beacon the privacy page had to
    // apologise for. The min.css references ../fonts/, so the copied layout
    // must preserve that relationship.
    { from: 'node_modules/boxicons/css/boxicons.min.css', to: 'public/vendor/boxicons/css/boxicons.min.css' },
    { from: 'node_modules/boxicons/fonts/boxicons.woff2', to: 'public/vendor/boxicons/fonts/boxicons.woff2' },
    { from: 'node_modules/boxicons/fonts/boxicons.woff', to: 'public/vendor/boxicons/fonts/boxicons.woff' },
    { from: 'node_modules/boxicons/fonts/boxicons.ttf', to: 'public/vendor/boxicons/fonts/boxicons.ttf' },
    // Legacy fallbacks the min.css still references; two small files beat a
    // stylesheet with dead URLs.
    { from: 'node_modules/boxicons/fonts/boxicons.eot', to: 'public/vendor/boxicons/fonts/boxicons.eot' },
    { from: 'node_modules/boxicons/fonts/boxicons.svg', to: 'public/vendor/boxicons/fonts/boxicons.svg' }
];

// Inter, self-hosted (F-039). The site loads weights 300–700 in the latin and
// latin-ext subsets — the same coverage the old Google Fonts URL provided for
// this content, minus the third-party request. @fontsource ships one css file
// per (subset, weight); they are concatenated into a single /vendor/inter.css
// with the url(./files/…) references rewritten to the copied layout. Each
// @font-face carries unicode-range, so browsers fetch only the subsets a page
// actually renders.
const INTER_WEIGHTS = [300, 400, 500, 600, 700];
const INTER_SUBSETS = ['latin', 'latin-ext'];

function vendorInter() {
    const pkg = resolve(root, 'node_modules/@fontsource/inter');
    let css = `/* Inter — self-hosted from @fontsource/inter (audit F-039).\n * Generated by tools/vendor-assets.mjs; do not edit by hand. */\n`;
    let fontCount = 0;
    for (const subset of INTER_SUBSETS) {
        for (const weight of INTER_WEIGHTS) {
            const part = resolve(pkg, `${subset}-${weight}.css`);
            try { statSync(part); } catch {
                console.error(`[vendor-assets] MISSING @fontsource/inter ${subset}-${weight}.css — run npm ci first.`);
                process.exit(1);
            }
            css += readFileSync(part, 'utf8').replaceAll('./files/', './inter/') + '\n';
            for (const ext of ['woff2', 'woff']) {
                const name = `inter-${subset}-${weight}-normal.${ext}`;
                const src = resolve(pkg, 'files', name);
                const dest = resolve(root, 'public/vendor/inter', name);
                mkdirSync(dirname(dest), { recursive: true });
                copyFileSync(src, dest);
                fontCount++;
            }
        }
    }
    const cssDest = resolve(root, 'public/vendor/inter.css');
    mkdirSync(dirname(cssDest), { recursive: true });
    writeFileSync(cssDest, css);
    console.log(`[vendor-assets] inter.css generated (${INTER_SUBSETS.length}×${INTER_WEIGHTS.length} faces, ${fontCount} font files)`);
}

let copied = 0;
for (const asset of ASSETS) {
    const src = resolve(root, asset.from);
    const dest = resolve(root, asset.to);
    try {
        statSync(src);
    } catch {
        // Fail the build loudly. A missing vendor file means index.html would
        // 404 on a script it needs, and a silently chartless dashboard is
        // exactly the kind of regression that reaches production.
        console.error(`[vendor-assets] MISSING ${asset.from}`);
        console.error('[vendor-assets] run `npm ci` (or `npm install`) first — these come from package-lock.json.');
        process.exit(1);
    }
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(src, dest);
    console.log(`[vendor-assets] ${asset.from} -> ${asset.to}`);
    copied++;
}
vendorInter();
console.log(`[vendor-assets] ${copied} asset(s) vendored into public/vendor/`);
